version: '3'

services:
  payload:
    image: oven/bun:latest
    ports:
      - '3000:3000'
    volumes:
      - .:/home/bun/app
      - node_modules:/home/bun/app/node_modules
    working_dir: /home/bun/app/
    command: sh -c "bun install && bun run dev"
    env_file:
      - .env

volumes:
  node_modules:
